
CREATE TABLE IF NOT EXISTS car_marks (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS car_categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cars (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  image_url TEXT,
  only_with_driver BOOLEAN NOT NULL DEFAULT FALSE,
  car_mark_id INT REFERENCES car_marks(id) ON DELETE SET NULL,
  car_category_id INT REFERENCES car_categories(id) ON DELETE SET NULL,
  price_per_day BIGINT NOT NULL CHECK (price_per_day >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS car_tags (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS car_car_tags (
  car_id INT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  car_tag_id INT NOT NULL REFERENCES car_tags(id) ON DELETE CASCADE,
  PRIMARY KEY (car_id, car_tag_id)
);