// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/nomad-pixel/imperial/internal/domain/usecases/auth"
	usecases2 "github.com/nomad-pixel/imperial/internal/domain/usecases/car"
	usecases3 "github.com/nomad-pixel/imperial/internal/domain/usecases/celebrity"
	usecases5 "github.com/nomad-pixel/imperial/internal/domain/usecases/driver"
	usecases4 "github.com/nomad-pixel/imperial/internal/domain/usecases/lead"
	"github.com/nomad-pixel/imperial/internal/interfaces/http/auth"
	"github.com/nomad-pixel/imperial/internal/interfaces/http/car"
	car5 "github.com/nomad-pixel/imperial/internal/interfaces/http/car/category"
	car2 "github.com/nomad-pixel/imperial/internal/interfaces/http/car/image"
	car4 "github.com/nomad-pixel/imperial/internal/interfaces/http/car/mark"
	car3 "github.com/nomad-pixel/imperial/internal/interfaces/http/car/tag"
	"github.com/nomad-pixel/imperial/internal/interfaces/http/celebrity"
	"github.com/nomad-pixel/imperial/internal/interfaces/http/driver"
	"github.com/nomad-pixel/imperial/internal/interfaces/http/lead"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies using Wire
func InitializeApp(ctx context.Context) (*App, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	pool, err := ProvideDatabase(ctx, config)
	if err != nil {
		return nil, err
	}
	tokenService := ProvideTokenService(config)
	userRepository := ProvideUserRepository(pool)
	signUpUsecase := usecases.NewSignUpUsecase(userRepository)
	verifyCodeRepository := ProvideVerifyCodeRepository(pool)
	emailService, err := ProvideEmailService(config)
	if err != nil {
		return nil, err
	}
	sendEmailVerificationUsecase := usecases.NewSendEmailVerificationUsecase(userRepository, verifyCodeRepository, emailService)
	confirmEmailVerificationUsecase := usecases.NewConfirmEmailVerificationUsecase(verifyCodeRepository, userRepository)
	signInUsecase := usecases.NewSignInUsecase(userRepository, tokenService)
	refreshTokenUsecase := usecases.NewRefreshTokenUsecase(tokenService)
	authHandler := auth.NewAuthHandler(signUpUsecase, sendEmailVerificationUsecase, confirmEmailVerificationUsecase, signInUsecase, refreshTokenUsecase)
	carRepository := ProvideCarRepository(pool)
	createCarUsecase := usecases2.NewCreateCarUsecase(carRepository)
	carImageRepository := ProvideCarImageRepository(pool)
	imageService, err := ProvideImageService(config)
	if err != nil {
		return nil, err
	}
	deleteCarUsecase := usecases2.NewDeleteCarUsecase(carRepository, carImageRepository, imageService)
	updateCarUsecase := usecases2.NewUpdateCarUsecase(carRepository)
	getCarByIdUsecase := usecases2.NewGetCarByIdUsecase(carRepository)
	getListCarsUsecase := usecases2.NewGetListCarsUsecase(carRepository)
	carHandler := car.NewCarHandler(createCarUsecase, deleteCarUsecase, updateCarUsecase, getCarByIdUsecase, getListCarsUsecase)
	createCarImageUsecase := usecases2.NewCreateCarImageUsecase(carImageRepository, imageService)
	deleteCarImageUsecase := usecases2.NewDeleteCarImageUsecase(carImageRepository, imageService)
	getCarImagesListUsecase := usecases2.NewGetCarImagesListUsecase(carImageRepository)
	carImageHandler := car2.NewCarImageHandler(createCarImageUsecase, deleteCarImageUsecase, getCarImagesListUsecase)
	carTagRepository := ProvideCarTagRepository(pool)
	createCarTagUsecase := usecases2.NewCreateCarTagUsecase(carTagRepository)
	getCarTagUsecase := usecases2.NewGetCarTagUsecase(carTagRepository)
	getCarTagsListUsecase := usecases2.NewGetCarTagsListUsecase(carTagRepository)
	updateCarTagUsecase := usecases2.NewUpdateCarTagUsecase(carTagRepository)
	deleteCarTagUsecase := usecases2.NewDeleteCarTagUsecase(carTagRepository)
	carTagHandler := car3.NewCarTagHandler(createCarTagUsecase, getCarTagUsecase, getCarTagsListUsecase, updateCarTagUsecase, deleteCarTagUsecase)
	carMarkRepository := ProvideCarMarkRepository(pool)
	createCarMarkUsecase := usecases2.NewCreateCarMarkUsecase(carMarkRepository)
	getCarMarkUsecase := usecases2.NewGetCarMarkUsecase(carMarkRepository)
	getCarMarksListUsecase := usecases2.NewGetCarMarksListUsecase(carMarkRepository)
	updateCarMarkUsecase := usecases2.NewUpdateCarMarkUsecase(carMarkRepository)
	deleteCarMarkUsecase := usecases2.NewDeleteCarMarkUsecase(carMarkRepository)
	carMarkHandler := car4.NewCarMarkHandler(createCarMarkUsecase, getCarMarkUsecase, getCarMarksListUsecase, updateCarMarkUsecase, deleteCarMarkUsecase)
	carCategoryRepository := ProvideCarCategoryRepository(pool)
	createCarCategoryUsecase := usecases2.NewCreateCarCategoryUsecase(carCategoryRepository)
	getCarCategoryUsecase := usecases2.NewGetCarCategoryUsecase(carCategoryRepository)
	getCarCategoriesListUsecase := usecases2.NewGetCarCategoriesListUsecase(carCategoryRepository)
	updateCarCategoryUsecase := usecases2.NewUpdateCarCategoryUsecase(carCategoryRepository)
	deleteCarCategoryUsecase := usecases2.NewDeleteCarCategoryUsecase(carCategoryRepository)
	carCategoryHandler := car5.NewCarCategoryHandler(createCarCategoryUsecase, getCarCategoryUsecase, getCarCategoriesListUsecase, updateCarCategoryUsecase, deleteCarCategoryUsecase)
	celebrityRepository := ProvideCelebrityRepository(pool)
	createCelebrityUsecase := usecases3.NewCreateCelebrityUsecase(celebrityRepository)
	uploadCelebrityImageUsecase := usecases3.NewUploadCelebrityImageUsecase(celebrityRepository, imageService)
	getCelebrityByIdUsecase := usecases3.NewGetCelebrityByIdUsecase(celebrityRepository)
	listCelebritiesUsecase := usecases3.NewListCelebritiesUsecase(celebrityRepository)
	updateCelebrityUsecase := usecases3.NewUpdateCelebrityUsecase(celebrityRepository)
	deleteCelebrityUsecase := usecases3.NewDeleteCelebrityUsecase(celebrityRepository, imageService)
	celebrityHandler := celebrity.NewCelebrityHandler(createCelebrityUsecase, uploadCelebrityImageUsecase, getCelebrityByIdUsecase, listCelebritiesUsecase, updateCelebrityUsecase, deleteCelebrityUsecase)
	leadRepository := ProvideLeadRepository(pool)
	createLeadUsecase := usecases4.NewCreateLeadUsecase(leadRepository)
	getLeadByIdUsecase := usecases4.NewGetLeadByIdUsecase(leadRepository)
	listLeadsUsecase := usecases4.NewListLeadsUsecase(leadRepository)
	deleteLeadUsecase := usecases4.NewDeleteLeadUsecase(leadRepository)
	leadHandler := lead.NewLeadHandler(createLeadUsecase, getLeadByIdUsecase, listLeadsUsecase, deleteLeadUsecase)
	driverRepository := ProvideDriverRepository(pool)
	createDriverUsecase := usecases5.NewCreateDriverUsecase(driverRepository)
	getDriverByIdUsecase := usecases5.NewGetDriverByIdUsecase(driverRepository)
	listDriversUsecase := usecases5.NewListDriversUsecase(driverRepository)
	updateDriverUsecase := usecases5.NewUpdateDriverUsecase(driverRepository)
	deleteDriverUsecase := usecases5.NewDeleteDriverUsecase(driverRepository)
	uploadDriverPhotoUsecase := usecases5.NewUploadDriverPhotoUsecase(driverRepository, imageService)
	driverHandler := driver.NewDriverHandler(createDriverUsecase, getDriverByIdUsecase, listDriversUsecase, updateDriverUsecase, deleteDriverUsecase, uploadDriverPhotoUsecase)
	app := NewApp(config, pool, tokenService, authHandler, carHandler, carImageHandler, carTagHandler, carMarkHandler, carCategoryHandler, celebrityHandler, leadHandler, driverHandler)
	return app, nil
}
